<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // user_id: de 3 à 12
        // user_id: (Développeur dans la table User) de 13 à 22
        // developer_id (table Developer): de 1 à 10
        // developer_prestation_id: de 1 à 6

        DB::table('orders')->insert([
            [
                'user_id'                  => 3,
                'developer_id'             => 1,
                'developer_prestation_id'  => 1,
                'instructions'             => "Bonjour, j’ai un site créé avec Wordpress et je rencontre des diffuseurs sur l'ajout d'un plugin. J'aimerais également mettre à jour la version de WordPress",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 4,
                'developer_id'             => 1,
                'developer_prestation_id'  => 2,
                'instructions'             => "Bonjour à vous, J’aimerais avoir un site vitrine à mon image et partager ma passion pour la cuisine",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => 0,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 5,
                'developer_id'             => 2,
                'developer_prestation_id'  => 3,
                'instructions'             => "Je suis très intéressé par la création d'un site e-commerce",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 6,
                'developer_id'             => 2,
                'developer_prestation_id'  => 4,
                'instructions'             => "Bonjour ! J'ai ouvert mon entreprise et je suis très intéressé par la création d'un logiciel ERP pour gérer la partie RH",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 7,
                'developer_id'             => 3,
                'developer_prestation_id'  => 5,
                'instructions'             => "Bonjour, je suis très intéressé par une application mobile pour gérer mon planning de rendez-vous",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => null,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 8,
                'developer_id'             => 3,
                'developer_prestation_id'  => 6,
                'instructions'             => "Bonsoir, J’aimerais avoir un site internet de type Blog mais avec un CRM (wordpress) pour avoir la main dessus",
                'is_payed'                 => 1,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => "cs_eidjdkjns123049njnjnjnjN394",
                'reference'                => "20221010esf1p",
                'is_finished'              => 1,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 9,
                'developer_id'             => 4,
                'developer_prestation_id'  => 7,
                'instructions'             => "Bonsoir, J’aimerais avoir un site internet pour mon activité de chauffeur VTC",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => null,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 10,
                'developer_id'             => 4,
                'developer_prestation_id'  => 7,
                'instructions'             => "Bonjour, j’aimerais faire connaître mon activité à travers un site vitrine avec un formulaire de contact.",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => null,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 11,
                'developer_id'             => 5,
                'developer_prestation_id'  => 8,
                'instructions'             => "Bonjour, Je suis développeur et j'ai un bug sur mon application web développée avec Symfony",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => 0,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 12,
                'developer_id'             => 5,
                'developer_prestation_id'  => 9,
                'instructions'             => "Bonsoir, Nous sommes une jeune entreprise et nous développer notre propre CRM",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 12,
                'developer_id'             => 6,
                'developer_prestation_id'  => 10,
                'instructions'             => "Bonjour, je suis intéressé par la création d'une API",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => null,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 4,
                'developer_id'             => 6,
                'developer_prestation_id'  => 11,
                'instructions'             => "Bonjour, j'ai un projet pour la création d'un jeu mobile de type tamagochi",
                'is_payed'                 => 1,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => "cs_ejeimapcnfur23jfoepap12jdie090",
                'reference'                => "20221224joyeuxnoel",
                'is_finished'              => 1,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 5,
                'developer_id'             => 7,
                'developer_prestation_id'  => 12,
                'instructions'             => "Bonjour, j'aimerais gérer les notes de frais et les absences de mes employés à travers un logiciel ERP ",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => null,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 6,
                'developer_id'             => 8,
                'developer_prestation_id'  => 13,
                'instructions'             => "Bonsoir, j'ai ouvert un restaurant et j'aimerais mettre en place un site avec mes menus et la possibilité de payer en ligne  ",
                'is_payed'                 => 0,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => null,
                'reference'                => null,
                'is_finished'              => 0,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 11,
                'developer_id'             => 9,
                'developer_prestation_id'  => 14,
                'instructions'             => "Bonsoir, j'ai une erreur 500 sur la page d'accueil de mon site",
                'is_payed'                 => 1,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => "cs_eidjdkjns123049njnjnjnjN394",
                'reference'                => "20221211etel",
                'is_finished'              => 1,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 5,
                'developer_id'             => 9,
                'developer_prestation_id'  => 15,
                'instructions'             => "Bonsoir, je suis cuisinier amateur et j'aimerais mettre en avant mes recettes",
                'is_payed'                 => 1,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => "cs_eidjdkjns123049njnjnjnjN394",
                'reference'                => "20221211delicious",
                'is_finished'              => 1,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
            [
                'user_id'                  => 8,
                'developer_id'             => 10,
                'developer_prestation_id'  => 16,
                'instructions'             => "Bonjour, j'ai un bug sur mon site web Wordpress, il m'est en effet impossible de soumettre mon formulaire de contact",
                'is_payed'                 => 1,
                'is_accepted_by_developer' => 1,
                'stripe_session_id'        => "cs_eidjdkjns123049njnjnjnjN394",
                'reference'                => "20221211delicious",
                'is_finished'              => 1,
                'created_at'               => '2022-09-25 10:50:12',
                'updated_at'               => '2022-09-26 15:25:52',
            ],
        ]);
    }
}
