@startuml Client
left to right direction

:Admin: as admin

package Application {
    usecase "Connection" as connection
    usecase "Add a new admin" as add_admin
    usecase "Moderation" as moderation
    usecase "Handle a dispute between if a developer or a client has a problem" as handle_dispute
}

admin --> connection
admin --> moderation
admin --> handle_dispute
admin --> add_admin
@enduml
