@startuml Client

:Admin: as admin

package users {
:Developer: as dev
:Client: as client
}

package Application {
    users --> (Sends a message to ask for help)
    (Sends a message to ask for help) --> admin
    admin .> (Sends a message to the person at fault)
    (Sends a message to the person at fault) --> users
}
@enduml
