@startuml Client
left to right direction

:Administrator: as admin

package Application {
    usecase auth as "Authentification"
    usecase moderation
    usecase handleDispute as "Handle disputes"
    usecase backOffice as "Back-Office
    --
    Stacks
    Orders
    Users
    Prestation types"
}

admin --> auth
admin --> moderation
admin --> handleDispute
admin --> backOffice
@enduml
