@startuml Client
left to right direction

:Client: as client

package Application {
    usecase "Inscription" as inscription
    usecase "Connection" as connection
    usecase see_devs as "See the list of developers available
    --
    Filter the devs"
    usecase see_profile as "see his profile
    --
    modify his profile"
    usecase "Feedback (note + comment)" as feedback
    usecase "Send message to admin" as send_message_to_admin
}

client --> inscription
client --> connection
client --> see_devs
client -> see_profile
client --> feedback
client --> send_message_to_admin
@enduml
