@startuml Developer
left to right direction

:Developer: as dev

package Application {
    usecase modify as "Modify his profile
    --
    Add a new prestation
    Modify a prestation
    Delete a prestation
    Add a new stack
    Delete a stack
    Modify his description"


    usecase missions as "
    Missions
    --
    See new missions
    See missions in progress
    See finished missions
    Set a mission to ''finished''
    "

    dev -> modify
    dev --> missions
}
@enduml
