@startuml Developer
left to right direction

:Developer: as dev

package Application {
    usecase "Inscription" as inscription
    usecase "Connection" as connection
    usecase "Acception new mission" as accept_mission
    usecase "Add type of developer" as add_type_of_developer
    usecase "Add number of years as a developer" as add_number_of_years
    usecase see_profile as  "see his profile
    --
    modify his profile"
}
dev --> connection
dev --> inscription
dev --> accept_mission
dev --> add_type_of_developer
dev -> add_number_of_years
dev -> see_profile
@enduml