@startuml
autonumber

actor Customer as U
actor Dev as V
box "Front-end"
participant View as A
end box

box "Back-end"
participant API as B
participant Mailer as D
participant DB as C
end box

activate A
U -> A : Clicks on a dev profile
A -> B : requests the dev information
activate B
B --> A : Returns the dev information
deactivate B
A --> U : Returns the dev information to the view
U -> A : Clicks to ask for a prestation
A --> U : Returns a modal
U -> A : Sends the message to the dev
A -> B : Creates a new prestation
activate B
B -> C : Stores in the database
B --> A : API returns the message to the view
deactivate B
B -> D : gives the email of the dev
activate D
A --> U : "New prestation sent !"
D --> V : "New prestation from DEVERR !"
deactivate D
deactivate A

@enduml
