@startuml
autonumber

actor User as U

box "Front-end"
participant View as A
end box

box "Back-end"
participant API as B
participant DB as C
end box

U -> A : clicks on the view
activate A

A -> B : Fetch all developers
activate B

B -> C : Request all developers
activate C

C  --> B : Returns all developers
deactivate C

B --> A : Request returned
deactivate B

A --> U : Done
deactivate A
@enduml
